name: Greeting on variable day

on:
  workflow_dispatch

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: windows-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday"
        run: set today=Monster; echo $Greeting $First_Name. $today. Today is $DAY_OF_WEEK!
        env:
          First_Name: ${{ vars.day_of_WEEK }}
